### ISSUE TITLE
Viewing is:offline systems no longer works -- no systems shown

### ISSUE THREAD

**Issue by tektrak** [wh1te909/tacticalrmm#854] opened 2021-12-11 12:08 UTC
As of the last couple of releases, the filtering to show is:offline systems no longer works. I can select is:online to see just those systems, but not is:offline. All the other availability filters do seem to work.

**Comment by dinger1986** [comment] 2021-12-11 12:09
can you provide a screenshot

**Comment by tektrak** [comment] 2021-12-11 12:15
Here are screenshots showing overdue and offline filters
<img width="1195" alt="Overdue" src="https://user-images.githubusercontent.com/71911954/145676171-0716e7b6-8968-4db2-9e0a-d6ef1a03a188.png">
<img width="1195" alt="Offline" src="https://user-images.githubusercontent.com/71911954/145676178-21db09e0-03b4-4ae0-b39a-9cbe8073cb01.png">
.

**Comment by dinger1986** [comment] 2021-12-11 12:23
Ok, so is: online works fine, is: offline shows overdue machines is: overdue shows offline devices so offline and overdue are showing the wrong status.

replicated as a bug

**Comment by wh1te909** [comment] 2021-12-13 23:20
I am not able to reproduce...see GIF below

![RaNbWK6xCe](https://user-images.githubusercontent.com/7434746/145904513-d0a27c50-6cbc-4aba-b413-5bf96c3ba9b5.gif)

**Comment by dinger1986** [comment] 2021-12-13 23:28
Offline in your gif is showing overdue not offline, isn't it?

**Comment by wh1te909** [comment] 2021-12-13 23:31
no it's showing offline lol
offline = yellow
overdue = red

![chrome_sxX26TFzj1](https://user-images.githubusercontent.com/7434746/145905654-c06646c1-2577-41cd-aac4-133762fd6ce9.png)

**Comment by dinger1986** [comment] 2021-12-13 23:39
Haha fair enough. Never looked at that before! Overdue to me would be over due by x amount of minutes and offline would be when it's been overdue for d amount of time. In that case working fine!! 

Closing now

**Closed** 2021-12-13 23:39 UTC
Labels: bug
