### ISSUE TITLE
Custom field type 'URL'

### ISSUE THREAD

**Issue by davidrudduck** [wh1te909/tacticalrmm#460] opened 2021-05-02 07:23 UTC
Here's my thought process.

We install ScreenConnect via script. It is technically possible to create a URL that calls the connection to ScreenConnect on that agent.

If we could define a custom field (client/site/agent) as 'URL' and it be clickable, you could use the output of a 'Check' script to populate the field and allow users to be able to quickly click to the relevant 3rd party tool page for that client/site/agent.

**Comment by wh1te909** [comment] 2021-05-02 07:33
duplicate of https://github.com/wh1te909/tacticalrmm/issues/277, closing

**Closed by wh1te909** 2021-05-02 07:33 UTC
