### ISSUE TITLE
UI issue: Able to Edit Agent Patch even when inheriting patch policy

### ISSUE THREAD

**Issue by subzdev** [wh1te909/tacticalrmm#185] opened 2020-11-19 22:40 UTC
When right-clicking on an client and clicking Edit - Patches, even though the agent has inherited a patch policy I am  able to still edit and save the days of the week and frequency even though they are greyed out.

**Comment by sadnub** [comment] 2020-11-20 00:06
@subzdev That is actually by design. Specifying it on the agent will override that setting in the patch policy.

**Comment by subzdev** [comment] 2020-11-20 22:10
The options are greyed out and the mouse pointer turns to a red circle with a line in the middle symbolizing the non-ability to make edits, but you can actually edit it.

**Comment by sadnub** [comment] 2020-11-24 22:54
I will check into this. Thanks for reporting!

**Comment by wh1te909** [comment] 2020-11-29 04:01
fixed, will be in the next release either later tonight or tmrw

**Closed by wh1te909** 2020-11-29 04:01 UTC
Labels: bug
