### ISSUE TITLE
Feature request: Permission for Users

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#382] opened 2021-04-11 08:32 UTC
It would be nice to be able to create users which f.ex only had access to a specific Client, Site or even Device.
We could then create user with limited access to Clients, Sites and devices.

As a MSP we often have individual IT-consultants we work with which have they own small customerbase and also would like to have a small RMM installed. Instead of using multiple RMM on the devices, they could log in to our RMM and just see their users. Perhaps based on tags? Or sites, client, devices.

**Comment by dinger1986** [comment] 2021-04-11 08:35
Duplicate of #162 feel free to add the above there

**Closed by dinger1986** 2021-04-11 08:35 UTC
