### ISSUE TITLE
Docker: No pending agent updates

### ISSUE THREAD

**Issue by gurhyj** [wh1te909/tacticalrmm#334] opened 2021-03-18 23:32 UTC
Docker: agents not updating from 1.4.7 to 1.4.9 or above inc 1.4.12.  No **pending action icon** for any agent even if manually select update agent, via agents update. Uninstall of existing agent to 1.4.7 and install of 1.4.9 works but still did not update to 1.4.11.  No Errors in debug log.

Have run prune database and remove orphaned actions. 
 
Manually running winagent-v1.4.12 upgrades the agent.

**Comment by sadnub** [comment] 2021-03-19 15:51
Can you see if you can generate an agent update package manually? Go to Agent > Install Agent and do the generated exe. It should generate and download. 

also no pending action will show if the agent is online and attempts to update. Maybe AV is catching it?

**Comment by wh1te909** [comment] 2021-03-19 22:18
Just tested on a fresh docker install, not able to reproduce:

Installed agent v1.4.12 (which is an old agent atm, current is 1.4.13) and then manually did Agents > Update Agents > Select All > Update

![dockerupdate1](https://user-images.githubusercontent.com/7434746/111847377-ea8d5d80-88c5-11eb-897a-4f0a1ad4f16b.PNG)

See screenshot above, it will actually create a pending action entry for the agent even if it's online, I added this recently.
Since agent was online it immediately received the update command, did the update and then around 30 seconds later, pending action is gone cuz it was completed:

![dockerupdate2](https://user-images.githubusercontent.com/7434746/111847510-304a2600-88c6-11eb-90c9-0e98caf1ca20.PNG)

**Comment by gurhyj** [comment] 2021-03-19 22:26
Will do I was just getting the following 

![image](https://user-images.githubusercontent.com/66262183/111848048-0f9fc180-8902-11eb-911d-9847c3e310a1.png)

**Comment by wh1te909** [comment] 2021-03-22 20:51
Hi this should be fixed now in latest release 0.4.28, turns out were some issues with background tasks not working in docker

**Closed** 2021-03-24 06:49 UTC
