### ISSUE TITLE
Feature request: New version alert

### ISSUE THREAD

**Issue by manc74** [wh1te909/tacticalrmm#453] opened 2021-04-29 07:24 UTC
**Describe the solution you'd like**
An icon or "vxx.xx available" next to the current version number if an update is available. This will alert the admin when a new version is available without needing to manually check github.

e,g.:
![rmmupdatemockup](https://user-images.githubusercontent.com/68019920/116515431-315a7400-a8c4-11eb-9f49-40e517e78c30.png)

**Comment by dinger1986** [comment] 2021-04-29 07:26
At the moment I believe this is by design so users have to check for any notes for upgrades rathe than just going for it and breaking it.

**Comment by wh1te909** [comment] 2021-04-29 08:16
@dinger1986 yea it's ok to just have a notification tho they'll still need to check github

@manc74 just added it, will be in next release. added a button that when clicked will open url in new tab to latest github release page

![feature-453](https://user-images.githubusercontent.com/7434746/116520858-208c0d00-a888-11eb-8d2a-e78b28f4a109.png)

**Comment by dinger1986** [comment] 2021-04-29 08:17
Nice!!

**Comment by manc74** [comment] 2021-04-29 08:21
Perfect! Thanks :)

**Comment by wh1te909** [comment] 2021-04-30 07:09
Released in 0.6.6

**Closed by wh1te909** 2021-04-30 07:09 UTC
Labels: enhancement
