### ISSUE TITLE
iPad OS - TRMM forces a logout when clicking on a machine in Safari

### ISSUE THREAD

**Issue by noahpeltier** [wh1te909/tacticalrmm#530] opened 2021-05-25 06:15 UTC
**Server Info (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: safari (iOS/iPad)
 - RMM Version (as shown in top left of web UI): v0.6.11

**Installation Method:**
  - [X ] Standard
  - [ ] Docker

**Agent Info (please complete the following information):**
- Agent version (as shown in the 'Summary' tab of the agent from web UI):
- Agent OS: [e.g. Win 10 v2004, Server 2012 R2]

**Describe the bug**
When using Safari (or any other browser) on an up-to-date iPad, Tactical RMM allows login and everything seems to behave normally until you click on a machine in the portal at which point TRMM will force a logout and display 401 unauthorized. 

**To Reproduce**
1. Go to Safari and log into TRMM
2. Click on any agent in the view panel 
3. Account is logged out and display 401 unauthorized error
4. This also behaves the same way in Chrome for iOS

**Expected behavior**
Expected behavior would be that browser is able to hold sessions the same as desktop would especially in the case of the iPad where it's version of Safari is a Desktop class browser. 

**Screenshots**

**Additional context**

**Comment by dinger1986** [comment] 2021-05-25 06:19
Duplicate of #43

**Closed** 2021-05-25 06:19 UTC
