### ISSUE TITLE
"Identify PC" option in Tactical agent 

### ISSUE THREAD

**Issue by abraham990201** [wh1te909/tacticalrmm#510] opened 2021-05-13 22:28 UTC
Hi! is it possible to add an "identify pc" option in the Tactical agent Icon that usually get displayed in the hidden icons tap?, so the clients can identify their pc in just seconds when calling for support.

**Comment by wh1te909** [comment] 2021-05-13 23:39
there is no agent that runs in the user session yet but it's planned
closing as this is a duplicate of #253

**Closed by wh1te909** 2021-05-13 23:39 UTC
