### ISSUE TITLE
scrolling issue when choosing run script

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#633] opened 2021-07-11 19:07 UTC
I tried ignoring it but I can't take it any longer :)
Maybe because the list isn't loaded fully? it loads the list as you scroll? 

See recording...

https://cdn.discordapp.com/attachments/736478043958149191/863858708689977364/scroll.gif

**Comment by silversword411** [comment] 2021-07-11 19:21
My hypothesis on the reason: https://discord.com/channels/736478043522072608/736478043958149191/863862004355301407

**Comment by wh1te909** [comment] 2021-07-13 19:03
this is by design, we lazy load the elements otherwise the render performance will lag
it should be resolved anyway i think you have another feature request to redesign the script window, i plan on making it into a table so we can add search and stuff

**Comment by wh1te909** [comment] 2021-08-30 06:37
fixed in 0.8.0

**Closed by wh1te909** 2021-08-30 06:37 UTC
Labels: fixed
