### ISSUE TITLE
Clickable linked alerts

### ISSUE THREAD

**Issue by DjMagicFingers** [wh1te909/tacticalrmm#574] opened 2021-06-13 00:33 UTC
The alarms that pop up at the corner of the screen are showing information only and beside the info, they only allow snoozing the alarm, marking it as resolved or going to all alarms screen.

My request is to make the informational PC name a clickable link to the relative PC that this alarm was triggered from.

The related PC is already listed as an information item - please change it to a link.

An enhancement for this could also be multi - level links - as one link to the PC, one link to the group etc.

![image](https://user-images.githubusercontent.com/32017425/121791920-b3de8f00-cbf7-11eb-86b5-124786adb03e.png)

**Comment by silversword411** [comment] 2021-06-14 02:21
Duplicate of #332 

Making Client, site and hostname will all be nice adds when it's gotten to.

**Closed by silversword411** 2021-06-14 02:21 UTC
