### ISSUE TITLE
Interactive script from interface

### ISSUE THREAD

**Issue by lapourgagner** [wh1te909/tacticalrmm#564] opened 2021-06-08 18:32 UTC
I searched a way to interactively run a script and i'ts complicated. I have to first upload the script and after connect to a remote terminal to finally execute my interactive script.

The idea is to create a functionality to do that automatically with a new menu like that:
![image](https://user-images.githubusercontent.com/31791162/121238426-616c3e00-c898-11eb-9d3c-c7fa106ac475.png)

**Comment by dinger1986** [comment] 2021-06-08 18:41
If it's a run once script would you not just use remote background with mesh?

**Comment by silversword411** [comment] 2021-06-08 18:53
Agree with @dinger1986 but I guess if remote background you could "pull" a script from the library that might be a nice Feature Request :)

**Comment by lapourgagner** [comment] 2021-06-08 18:53
It's what I use for now but it's messy to manage many scripts among many pc, as the scripts manager is good.

**Comment by lapourgagner** [comment] 2021-06-08 18:55
@silversword411 I haven't think in this way but it could absolutley fit in

**Comment by dinger1986** [comment] 2021-06-08 19:16
To pull set scripts into remote background that would be a mesh feature.

Guess there's so many ways to do it.

Are you adding in variables or something?

**Comment by sadnub** [comment] 2021-06-08 21:35
Are you looking for an experience similar to powershell ise?

**Comment by lapourgagner** [comment] 2021-06-08 22:36
> 
> 
> Are you looking for an experience similar to powershell ise?

I'm not sure to understand what do you mean. The script editor integrated to TacticalRMM is ok. My issue is to manage and run interactive scripts (What I mean by interactive is it require me to type something) on agents.

**Comment by lapourgagner** [comment] 2021-06-08 22:41
> To pull set scripts into remote background that would be a mesh feature.
I agree

> Guess there's so many ways to do it.
Porbably, I havn't look in detail about script sync but have you an example ?

> Are you adding in variables or something?
One more no really sure to understand, Are you talking about customs fields or PowerShell varables ?

**Comment by wh1te909** [comment] 2021-06-11 06:38
is this a duplicate of #502 ?

**Comment by lapourgagner** [comment] 2021-06-13 22:05
> is this a duplicate of #502 ?

I don't think so. #502 is about running script from script editor.

Me, I want to be able to interact with a script, type things, without having to manually transfer the script, connect to remote shell to run it.

**Comment by wh1te909** [comment] 2021-06-17 02:53
> > is this a duplicate of #502 ?
> 
> I don't think so. #502 is about running script from script editor.
> 
> Me, I want to be able to interact with a script, type things, without having to manually transfer the script, connect to remote shell to run it.

still not understanding. can you give me an example of how you would do this without an rmm (like if you're just on the pc) so we can understand what you want us to implement

**Comment by lapourgagner** [comment] 2021-06-19 18:57
> still not understanding. can you give me an example of how you would do this without an rmm (like if you're just on the pc) so we can understand what you want us to implement

I mean anaything that expect input like:
`$ping = Read-Host -Prompt "What host do you want to ping?"`
`ping $ping`

**Comment by wh1te909** [comment] 2021-06-24 01:58
start menu > search for "windows powershell ISE" open that and let me know if you're looking for something like that but in a web interface

otherwise you can just use the remote shell feature to interactively run powershell, see screenshot below (right click on the connect button)

![mesh_ps](https://user-images.githubusercontent.com/7434746/123190695-e0df3d00-d454-11eb-8dcc-ecb64ea33858.png)

**Comment by lapourgagner** [comment] 2021-06-24 12:40
I'm not looking for an editor.

Let's take the example of my script:
I create a new script in the script manager, the script is
`$ping = Read-Host -Prompt "What host do you want to ping?"`
`ping $ping`

After that, I right clic on a desktop, click 'Run script', I choose my newly created script but i get `Read-Host : Windows PowerShell n'est pas en mode interactif. La fonctionnalit de lecture et d'invite n'est pas disponible.`
In english this is something like 'Powershell is not in interactive mode. The fonctionalitiy of input reading is not available'

**Comment by silversword411** [comment] 2021-09-21 12:06
I understand what's asked for, but this seems like a script that should either be based on parameters, or you should run it interactively with background. 

I'm going to mark as closed/wontfix and that can be revised in future if necessary.

**Closed** 2021-09-21 12:06 UTC
Labels: enhancement, wontfix
