### ISSUE TITLE
Feature : Allow text block in custom field (instead of varchar?)

### ISSUE THREAD

**Issue by bbrendon** [wh1te909/tacticalrmm#533] opened 2021-05-26 20:02 UTC
Right now it seems only one line of text (varchar?) is collected in the text type custom field. It would be nice if text blocks could be saved. 

I suppose a current workaround would be to remove all the CRLF and save it. I haven't tried, but I'm guessing it might work. Formatting would be gone of course.

**Comment by wh1te909** [comment] 2021-05-27 07:10
the db field is actually a text field, not a varchar. I changed the UI to allow text blocks

**Comment by bbrendon** [comment] 2021-05-28 00:55
@wh1te909  I think in order to resolve this the collector also needs to be adjusted. I believe it only collects the first line.

**Comment by sadnub** [comment] 2021-05-28 03:06
This is by design actually. I had to grab the last line of stdout otherwise any output before the actual value would be captured.

**Comment by bbrendon** [comment] 2021-05-28 06:17
@sadnub can this issue be reopened? Is this a possible feature to add?

**Comment by sadnub** [comment] 2021-05-28 11:52
What's your use case? Currently it will split the stdout on \n and grab the last output. Even doing a return at the end of a ps script will just append that to stdout.

This behavior could be turned off with a checkbox, but the text might not show correctly in the dashboard

**Comment by bbrendon** [comment] 2021-05-28 18:04
The use case I’m thinking is to save and view bitlocker keys and IDs for the agents.

**Comment by sadnub** [comment] 2021-05-28 19:17
What I'm thinking is to create another type of custom field called Text Area and in the collector there can be a box that says "save all output". That will just save stdout to the custom field. It will actually just be the same as looking at the script results of the collector.

**Comment by bbrendon** [comment] 2021-05-28 19:59
@dinger1986 not a bad idea but that requires manual effort.

**Comment by dinger1986** [comment] 2021-05-28 20:04
Atm but maybe something @sadnub or @wh1te909 can change?

I wrote a script that grabs the keys for bitlocker and writes it to a folder in c:\

**Comment by wh1te909** [comment] 2021-05-29 05:19
released in 0.6.12

**Closed by wh1te909** 2021-05-29 05:19 UTC
Labels: enhancement, fixed

**Comment by bbrendon** [comment] 2021-05-29 05:56
Updated and refreshed the page. I don't see the field...

![image](https://user-images.githubusercontent.com/6364477/120059677-c5287880-c007-11eb-856b-c592c8d67d39.png)

**Comment by bbrendon** [comment] 2021-05-29 05:57
nm. found it. !  
"Save all output (Only for text area)"
