### ISSUE TITLE
[feature request] patch managementt

### ISSUE THREAD

**Issue by Sedlise** [wh1te909/tacticalrmm#566] opened 2021-06-09 14:39 UTC
Hi,

is it possible to add the function patch management.
ie approve a KB for all / a client / a site or disapprove.

Thanks

**Comment by bleglord** [comment] 2021-06-09 15:18
> Hi,
> 
> is it possible to add the function patch management.
> ie approve a KB for all / a client / a site or disapprove.
> 
> Thanks

I think you can do this manually (set everything to manual approval on the policy, then manually select the KB's after) but I don't think it can be done in bulk which would be nice.

Another thing to piggyback on this: Is there a way to prevent Win10's automatic updates/check for updates when patching is managed by Tactical? It seems that while tactical can prompt/force a patch when wanted, if a patch is scheduled for Thursday, but the computer attempts to auto-update on Tuesday, it will pull the patch on Tuesday instead of being held until the scheduled date.

**Comment by wh1te909** [comment] 2021-06-10 21:54
duplicate of #179

**Closed by wh1te909** 2021-06-10 21:54 UTC
