### ISSUE TITLE
Reset Check Status - delay checks

### ISSUE THREAD

**Issue by frankemann** [wh1te909/tacticalrmm#850] opened 2021-12-10 07:53 UTC
It would be great to be able to reset the check status for X amount of hours (or 24 h), or until next day (00.00).

The use case is if we have a backup check, we investigate the error and fix it, the error check will return at next check because our scripts are checking for error in eventlogs for the last 24hours.

**Comment by silversword411** [comment] 2021-12-10 08:09
Dupe of #849

**Closed by silversword411** 2021-12-10 08:09 UTC
