### ISSUE TITLE
Feature Request: Add group of devices

### ISSUE THREAD

**Issue by Kalltech** [wh1te909/tacticalrmm#613] opened 2021-07-01 14:53 UTC
We want a menu where we can create a group of devices independently of the company. But keep our structure by company.

**Describe the solution you'd like**
We want to deploy or schedule a task on several devices, for example a same task on all the exchanges of several different companies

**Describe alternatives you've considered**
At this time, we can make a research, select the devices and add the task

Thanks guys for all this great work!

**Comment by silversword411** [comment] 2021-07-02 14:11
Duplicate of #553

**Closed by silversword411** 2021-07-02 14:11 UTC
Labels: duplicate
